classes:
  - system.linux.system.single
  - system.linux.system.repo.mcp.extra
  - system.linux.system.repo.mcp.salt
  - system.linux.system.repo.ubuntu
  - system.openssh.server.team.lab
  - system.openssh.server.team.members.tkukral
parameters:
  _param:
    # infra service addresses
    infra_config_hostname: cfg01
    infra_config_address: 192.168.0.10
    infra_config_deploy_address: ${_param:infra_config_address}

#    cluster_domain: dummy.local
#    cluster_name: dummy
    apt_mk_version: nightly
  linux:
    network:
      resolv:
        dns:
          - 192.168.0.2
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
            - ${_param:infra_config_hostname}
            - ${_param:infra_config_hostname}.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
