classes:
  - system.linux.system.single
  - system.linux.system.repo.mcp.salt
  - system.linux.system.repo.ubuntu
  - system.openssh.server.team.members.tkukral
parameters:
  _param:
    # infra service addresses
    infra_config_hostname: cfg01
    infra_config_address: 127.0.0.1
    infra_config_deploy_address: ${_param:infra_config_address}
    master_hostname: ${_param:infra_config_hostname}
    master_address: ${_param:infra_config_address}
    control_address: ${_param:infra_config_address}
    apt_mk_version: nightly
    linux_system_user_sudo: true
  linux:
    network:
      resolv:
        dns:
          - 192.168.0.2
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
            - ${_param:infra_config_hostname}
            - ${_param:infra_config_hostname}.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
